sugarcrm:
  image: cloud2/sugarcrm
  container_name: sugarcrm
  ports:
    - "2080:80"
  volumes:
    - /var/www/html
  links:
    - "db"
  environment:
    DB_TYPE: mysql
    DB_TCP_PORT: 3306
    DB_MANAGER: MysqlManager
    DB_HOST_NAME: mysql
    DATABASE_NAME: sugarcrm 
    DB_USER_NAME: sugarcrm
    DB_PASSWORD: gQ8GLq761jfp
    
db:
  image: mysql
  container_name: mysql
  volumes:
    - /var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: o5qbBYT7DS6b
    MYSQL_DATABASE: sugarcrm
    MYSQL_USER: sugarcrm
    MYSQL_PASSWORD: gQ8GLq761jfp
  mem_limit: 1024m
